name: Post Trump Fact to Bluesky

on:
  schedule:
    - cron: '0 */2 * * *'  # Every 2 hours
  workflow_dispatch:       # Allow manual trigger too

jobs:
  post:
    runs-on: ubuntu-latest

    env:
      BSKY_USERNAME: ${{ secrets.BSKY_USERNAME }}
      BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot (random chance to post)
        run: |
          echo "USERNAME bytes: $(echo -n "${BSKY_USERNAME}" | wc -c)"
          echo "APP_PASSWORD bytes: $(echo -n "${BSKY_APP_PASSWORD}" | wc -c)"
          python trump_bot.py
